# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.9-alpine.3.14"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.9-alpine.3.14"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.9-alpine.3.14"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.9-alpine.3.14"
  i386: "ghcr.io/home-assistant/i386-base-python:3.9-alpine.3.14"
labels:
  org.opencontainers.image.title: "BeardedTek frigate Event Video Recorder"
  org.opencontainers.image.description: "Provides frigate Event Video Recorder as a HASSIO addon"
  org.opencontainers.image.source: "https://github.com/BeardedTek-com/hassio-addons/fevr/"
  org.opencontainers.image.licenses: "AGPL v3"
args:
  TEMPIO_VERSION: "2021.09.0"
