# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: fevr
version: "0.3.31"
slug: fevr
description: frigate Event Video Recorder v0.3 HASSIO addon
url: "https://github.com/beardedtek-com/fEVR/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
panel_icon: mdi:cctv
ports:
  5080/tcp: 5080
  5081/tcp: 5081
ports_description:
  5080/tcp: Web Interface
  5081/tcp: sqlite_web
ingress: true
ingress_port: 5080
ingress_entry: /
panel_admin: false
panel_icon: "mdi:cctv"
panel_title: fEVR
startup: services
image: ghcr.io/beardedtek-com/fevr-{arch}
options:
  debug: "false"
  title: "My Home"
  frigate: "http://frigate.local:5000"
schema:
  debug: str
  title: str
  frigate: str
