# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: fEVR
version: "0.6.17"
slug: fevr
description: frigate Event Video Recorder v0.6-RC HASSIO addon
url: "https://github.com/beardedtek-com/fEVR/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: true
init: false
panel_icon: mdi:cctv
ports:
  5180/tcp: 5180
ports_description:
  5180/tcp: Web Interface
ingress: true
ingress_port: 0
panel_admin: false
panel_icon: "mdi:cctv"
panel_title: fEVR
startup: services
image: ghcr.io/beardedtek-com/fevr-{arch}
