# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: fEVR
version: "0.6.06"
slug: fevr
description: frigate Event Video Recorder v0.6-RC HASSIO addon
url: "https://github.com/beardedtek-com/fEVR/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
panel_icon: mdi:cctv
ports:
  5090/tcp: 5090
ports_description:
  5090/tcp: Web Interface
ingress: true
ingress_port: 5090
ingress_entry: /
panel_admin: false
panel_icon: "mdi:cctv"
panel_title: fEVR
startup: services
image: ghcr.io/beardedtek-com/fevr-{arch}
options:
  FLASK_ENV: "production"
  FEVR_PORT: "5090"
  MQTT_CLIENT: "true"
schema:
  debug: str
  title: str
  frigate: str
