# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: nutUI
version: "0.1.3"
slug: nutui
description: A modern web ui for nut attached UPS
url: "https://github.com/beardedtek-com/nutui"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
image: "ghcr.io/beardedtek-com/{arch}-nutui"
